### ISSUE TITLE
Feature Request: cursor in typing bar / up/down scrolling history 

### ISSUE THREAD

**Issue by danrobi11** [tofudd/lanchat#9]
Theres no cursor in typing bar, makes it a bit hard to deal with typos ect.  

Would be very handy to be able to have the up/down scrolling previously typed history.

**Comment by tofudd** [comment]
You can scroll history with up/down arrows. Cursor exists but it's invisible in some terminal emulators.

**Comment by danrobi11** [comment]
> You can scroll history with up/down arrows

Not here.

**Comment by tofudd** [comment]
That's weird. I checked it in tilix-1.9.3-6 and it work's properly.

**Comment by danrobi11** [comment]
same in xterm(344)

**Comment by tofudd** [comment]
It also works in xterm 359. Do you use the arrows on your keyboard or on the scroll bar? My previous message may be unclear. Scrolling is possible with the up / down arrows on the keyboard. Terminal scroll bar does not work.

**Comment by danrobi11** [comment]
yes with the up / down arrows on the keyboard

**Comment by tofudd** [comment]
Honestly I don't know why it's happening to you. I'll check it later with specific versions that you mentioned to reproduce this problem more accurately.

**Comment by danrobi11** [comment]
> I don't know why it's happening to you

Ya thats weird.
well heres my PC info if that can help

```
OS: MX 19.3 (patito feo) x86_64 based Debian GNU/Linux 10 (buster)
SysV init version: 2.93
Kernel: 4.19.0-9-amd64
Xorg v1:7.7+19
WM: Spectrwm
Theme: Arc-Darker [GTK2/3]
Icons: Moka [GTK2/3]
```

**Comment by tofudd** [comment]
Ok I think I've got it. You meant `previously typed history` and I misunderstanded it. You can scroll the history of sent and received messages, but currently there is no way to get previous commands back into editi field. I'll see what can be done with it but I'm limited with ConsoleGUI library.

**Comment by tofudd** [comment]
Added in 5733936. I'll merge this changes in upcoming 2.7 release.

**Comment by danrobi11** [comment]
I updated kitty to v 20.1 and I now have a prompt. Up/down still doesnt show previously typed message

**Comment by tofudd** [comment]
This will be added in new update. If you need it right now you can build source from [2.7 branch](https://github.com/tofudd/lanchat/tree/2.7).

**Comment by danrobi11** [comment]
Okay. Now I think the prompt issue was probably due to a theme. I never thought about that. My bad.
